/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GlapTemplateDetailService } from "../glapTemplateDetail.service";
import { GlapTemplateDetailCreateInput } from "./GlapTemplateDetailCreateInput";
import { GlapTemplateDetailWhereInput } from "./GlapTemplateDetailWhereInput";
import { GlapTemplateDetailWhereUniqueInput } from "./GlapTemplateDetailWhereUniqueInput";
import { GlapTemplateDetailFindManyArgs } from "./GlapTemplateDetailFindManyArgs";
import { GlapTemplateDetailUpdateInput } from "./GlapTemplateDetailUpdateInput";
import { GlapTemplateDetail } from "./GlapTemplateDetail";

export class GlapTemplateDetailControllerBase {
  constructor(protected readonly service: GlapTemplateDetailService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GlapTemplateDetail })
  async create(
    @common.Body() data: GlapTemplateDetailCreateInput
  ): Promise<GlapTemplateDetail> {
    return await this.service.create({
      data: data,
      select: {
        camount: true,
        dpercent: true,
        dretention: true,
        hacct: true,
        hcategory: true,
        hcontract: true,
        hcostcode: true,
        hglaptemplate: true,
        hjob: true,
        hproperty: true,
        hvattrantype: true,
        id: true,
        snotes: true,
        ssegment1: true,
        ssegment10: true,
        ssegment11: true,
        ssegment12: true,
        ssegment2: true,
        ssegment3: true,
        ssegment4: true,
        ssegment5: true,
        ssegment6: true,
        ssegment7: true,
        ssegment8: true,
        ssegment9: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [GlapTemplateDetail] })
  @ApiNestedQuery(GlapTemplateDetailFindManyArgs)
  async findMany(
    @common.Req() request: Request
  ): Promise<GlapTemplateDetail[]> {
    const args = plainToClass(GlapTemplateDetailFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        camount: true,
        dpercent: true,
        dretention: true,
        hacct: true,
        hcategory: true,
        hcontract: true,
        hcostcode: true,
        hglaptemplate: true,
        hjob: true,
        hproperty: true,
        hvattrantype: true,
        id: true,
        snotes: true,
        ssegment1: true,
        ssegment10: true,
        ssegment11: true,
        ssegment12: true,
        ssegment2: true,
        ssegment3: true,
        ssegment4: true,
        ssegment5: true,
        ssegment6: true,
        ssegment7: true,
        ssegment8: true,
        ssegment9: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GlapTemplateDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: GlapTemplateDetailWhereUniqueInput
  ): Promise<GlapTemplateDetail | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        camount: true,
        dpercent: true,
        dretention: true,
        hacct: true,
        hcategory: true,
        hcontract: true,
        hcostcode: true,
        hglaptemplate: true,
        hjob: true,
        hproperty: true,
        hvattrantype: true,
        id: true,
        snotes: true,
        ssegment1: true,
        ssegment10: true,
        ssegment11: true,
        ssegment12: true,
        ssegment2: true,
        ssegment3: true,
        ssegment4: true,
        ssegment5: true,
        ssegment6: true,
        ssegment7: true,
        ssegment8: true,
        ssegment9: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GlapTemplateDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: GlapTemplateDetailWhereUniqueInput,
    @common.Body() data: GlapTemplateDetailUpdateInput
  ): Promise<GlapTemplateDetail | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          camount: true,
          dpercent: true,
          dretention: true,
          hacct: true,
          hcategory: true,
          hcontract: true,
          hcostcode: true,
          hglaptemplate: true,
          hjob: true,
          hproperty: true,
          hvattrantype: true,
          id: true,
          snotes: true,
          ssegment1: true,
          ssegment10: true,
          ssegment11: true,
          ssegment12: true,
          ssegment2: true,
          ssegment3: true,
          ssegment4: true,
          ssegment5: true,
          ssegment6: true,
          ssegment7: true,
          ssegment8: true,
          ssegment9: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GlapTemplateDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: GlapTemplateDetailWhereUniqueInput
  ): Promise<GlapTemplateDetail | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          camount: true,
          dpercent: true,
          dretention: true,
          hacct: true,
          hcategory: true,
          hcontract: true,
          hcostcode: true,
          hglaptemplate: true,
          hjob: true,
          hproperty: true,
          hvattrantype: true,
          id: true,
          snotes: true,
          ssegment1: true,
          ssegment10: true,
          ssegment11: true,
          ssegment12: true,
          ssegment2: true,
          ssegment3: true,
          ssegment4: true,
          ssegment5: true,
          ssegment6: true,
          ssegment7: true,
          ssegment8: true,
          ssegment9: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
