export type GlAllocateHistory = {
  hacct: number;
  hbatch: bigint;
  hje: bigint;
  hppty: number;
  ibook: number;
  id: number;
  sbegin: number;
  sbeginbudget: number;
  sbudget: number;
  smtd: number;
  ssegment1: string;
  ssegment10: string;
  ssegment11: string;
  ssegment12: string;
  ssegment2: string;
  ssegment3: string;
  ssegment4: string;
  ssegment5: string;
  ssegment6: string;
  ssegment7: string;
  ssegment8: string;
  ssegment9: string;
  umonth: Date;
};
