import { BigIntFilter } from "../../util/BigIntFilter";
import { IntFilter } from "../../util/IntFilter";
import { StringFilter } from "../../util/StringFilter";

export type GlAllocateWhereInput = {
  bcustomsource?: BigIntFilter;
  haccttree?: IntFilter;
  haccttreedetail?: IntFilter;
  hchart?: IntFilter;
  hoffsetacct?: IntFilter;
  ibalancebydetails?: IntFilter;
  ibalancingsource?: BigIntFilter;
  iconsolidatebooks?: IntFilter;
  id?: IntFilter;
  idelta?: IntFilter;
  idetail?: IntFilter;
  iincludesourcesegments?: IntFilter;
  iincludeuserdeffields?: IntFilter;
  iintercompany?: IntFilter;
  ipropertysegment?: IntFilter;
  ireverseje?: IntFilter;
  isqftcolumn?: IntFilter;
  isuppresssegment?: IntFilter;
  iunpostbatch?: IntFilter;
  scode?: StringFilter;
  scolumnname?: StringFilter;
  sdatecolumn?: StringFilter;
  sfrombook?: StringFilter;
  sname?: StringFilter;
  snotes?: StringFilter;
  sreference?: StringFilter;
  ssourcecolumnname?: StringFilter;
  ssourcedatecolumn?: StringFilter;
  ssourcetablename?: StringFilter;
  ssourcetype?: StringFilter;
  stablename?: StringFilter;
  stype?: StringFilter;
  suserdef1?: StringFilter;
  suserdef2?: StringFilter;
  suserdef3?: StringFilter;
  suserdef4?: StringFilter;
  suserdef5?: StringFilter;
  suserdef6?: StringFilter;
  suserdef7?: StringFilter;
  suserdef8?: StringFilter;
};
