import { SortOrder } from "../../util/SortOrder";

export type GlAllocateOrderByInput = {
  bcustomsource?: SortOrder;
  haccttree?: SortOrder;
  haccttreedetail?: SortOrder;
  hchart?: SortOrder;
  hoffsetacct?: SortOrder;
  ibalancebydetails?: SortOrder;
  ibalancingsource?: SortOrder;
  iconsolidatebooks?: SortOrder;
  id?: SortOrder;
  idelta?: SortOrder;
  idetail?: SortOrder;
  iincludesourcesegments?: SortOrder;
  iincludeuserdeffields?: SortOrder;
  iintercompany?: SortOrder;
  ipropertysegment?: SortOrder;
  ireverseje?: SortOrder;
  isqftcolumn?: SortOrder;
  isuppresssegment?: SortOrder;
  iunpostbatch?: SortOrder;
  scode?: SortOrder;
  scolumnname?: SortOrder;
  sdatecolumn?: SortOrder;
  sfrombook?: SortOrder;
  sname?: SortOrder;
  snotes?: SortOrder;
  sreference?: SortOrder;
  ssourcecolumnname?: SortOrder;
  ssourcedatecolumn?: SortOrder;
  ssourcetablename?: SortOrder;
  ssourcetype?: SortOrder;
  stablename?: SortOrder;
  stype?: SortOrder;
  suserdef1?: SortOrder;
  suserdef2?: SortOrder;
  suserdef3?: SortOrder;
  suserdef4?: SortOrder;
  suserdef5?: SortOrder;
  suserdef6?: SortOrder;
  suserdef7?: SortOrder;
  suserdef8?: SortOrder;
};
