/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateUser1Args } from "./CreateUser1Args";
import { UpdateUser1Args } from "./UpdateUser1Args";
import { DeleteUser1Args } from "./DeleteUser1Args";
import { User1CountArgs } from "./User1CountArgs";
import { User1FindManyArgs } from "./User1FindManyArgs";
import { User1FindUniqueArgs } from "./User1FindUniqueArgs";
import { User1 } from "./User1";
import { BidFindManyArgs } from "../../bid/base/BidFindManyArgs";
import { Bid } from "../../bid/base/Bid";
import { JobFindManyArgs } from "../../job/base/JobFindManyArgs";
import { Job } from "../../job/base/Job";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { ReviewFindManyArgs } from "../../review/base/ReviewFindManyArgs";
import { Review } from "../../review/base/Review";
import { SkillFindManyArgs } from "../../skill/base/SkillFindManyArgs";
import { Skill } from "../../skill/base/Skill";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { User1Service } from "../user1.service";
@graphql.Resolver(() => User1)
export class User1ResolverBase {
  constructor(protected readonly service: User1Service) {}

  async _user1sMeta(
    @graphql.Args() args: User1CountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [User1])
  async user1s(@graphql.Args() args: User1FindManyArgs): Promise<User1[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => User1, { nullable: true })
  async user1(
    @graphql.Args() args: User1FindUniqueArgs
  ): Promise<User1 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => User1)
  async createUser1(@graphql.Args() args: CreateUser1Args): Promise<User1> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => User1)
  async updateUser1(
    @graphql.Args() args: UpdateUser1Args
  ): Promise<User1 | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => User1)
  async deleteUser1(
    @graphql.Args() args: DeleteUser1Args
  ): Promise<User1 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Bid], { name: "bids" })
  async resolveFieldBids(
    @graphql.Parent() parent: User1,
    @graphql.Args() args: BidFindManyArgs
  ): Promise<Bid[]> {
    const results = await this.service.findBids(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Job], { name: "jobs" })
  async resolveFieldJobs(
    @graphql.Parent() parent: User1,
    @graphql.Args() args: JobFindManyArgs
  ): Promise<Job[]> {
    const results = await this.service.findJobs(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Message], { name: "receivedMessages" })
  async resolveFieldReceivedMessages(
    @graphql.Parent() parent: User1,
    @graphql.Args() args: MessageFindManyArgs
  ): Promise<Message[]> {
    const results = await this.service.findReceivedMessages(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Review], { name: "reviewsAsClient" })
  async resolveFieldReviewsAsClient(
    @graphql.Parent() parent: User1,
    @graphql.Args() args: ReviewFindManyArgs
  ): Promise<Review[]> {
    const results = await this.service.findReviewsAsClient(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Review], { name: "reviewsAsFreelancer" })
  async resolveFieldReviewsAsFreelancer(
    @graphql.Parent() parent: User1,
    @graphql.Args() args: ReviewFindManyArgs
  ): Promise<Review[]> {
    const results = await this.service.findReviewsAsFreelancer(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Message], { name: "sentMessages" })
  async resolveFieldSentMessages(
    @graphql.Parent() parent: User1,
    @graphql.Args() args: MessageFindManyArgs
  ): Promise<Message[]> {
    const results = await this.service.findSentMessages(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Skill], { name: "skills" })
  async resolveFieldSkills(
    @graphql.Parent() parent: User1,
    @graphql.Args() args: SkillFindManyArgs
  ): Promise<Skill[]> {
    const results = await this.service.findSkills(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Transaction], { name: "transactionsAsClient" })
  async resolveFieldTransactionsAsClient(
    @graphql.Parent() parent: User1,
    @graphql.Args() args: TransactionFindManyArgs
  ): Promise<Transaction[]> {
    const results = await this.service.findTransactionsAsClient(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Transaction], {
    name: "transactionsAsFreelancer",
  })
  async resolveFieldTransactionsAsFreelancer(
    @graphql.Parent() parent: User1,
    @graphql.Args() args: TransactionFindManyArgs
  ): Promise<Transaction[]> {
    const results = await this.service.findTransactionsAsFreelancer(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }
}
