export type GlapTemplateDetailUpdateInput = {
  camount?: number;
  dpercent?: number;
  dretention?: number;
  hacct?: number;
  hcategory?: number;
  hcontract?: number;
  hcostcode?: number;
  hglaptemplate?: number;
  hjob?: number;
  hproperty?: number;
  hvattrantype?: number;
  snotes?: string;
  ssegment1?: string;
  ssegment10?: string;
  ssegment11?: string;
  ssegment12?: string;
  ssegment2?: string;
  ssegment3?: string;
  ssegment4?: string;
  ssegment5?: string;
  ssegment6?: string;
  ssegment7?: string;
  ssegment8?: string;
  ssegment9?: string;
};
